# Generated by Django 5.2.7 on 2025-11-11 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_usertime_finish_time_alter_usertime_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='usertime',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='usertime',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='usertime',
            index=models.Index(fields=['user', 'date'], name='employees_u_user_id_1e00f6_idx'),
        ),
    ]
